"""Add created_at to User model

Revision ID: 05fa98ae7f20
Revises: 88088a8428a6
Create Date: 2025-09-15 23:06:26.179830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05fa98ae7f20'
down_revision = '88088a8428a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=False))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###