"""Add new fields to models

Revision ID: 4473d938c06a
Revises: 05fa98ae7f20
Create Date: 2025-09-16 13:37:06.554007

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4473d938c06a'
down_revision = '05fa98ae7f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('essay', sa.Text(), nullable=True))
    op.add_column('application', sa.Column('submission_date', sa.DateTime(), nullable=True))
    op.add_column('application', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.add_column('application', sa.Column('reviewed_by', sa.Integer(), nullable=True))
    op.add_column('application', sa.Column('notes', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'application', 'user', ['reviewed_by'], ['id'])
    op.drop_column('application', 'created_at')
    op.add_column('scholarship', sa.Column('eligibility_criteria', sa.Text(), nullable=True))
    op.add_column('scholarship', sa.Column('contact_email', sa.String(length=120), nullable=True))
    op.add_column('scholarship', sa.Column('website', sa.String(length=200), nullable=True))
    op.add_column('scholarship', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('scholarship', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('scholarship', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'scholarship', 'user', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scholarship', type_='foreignkey')
    op.drop_column('scholarship', 'created_at')
    op.drop_column('scholarship', 'created_by')
    op.drop_column('scholarship', 'is_active')
    op.drop_column('scholarship', 'website')
    op.drop_column('scholarship', 'contact_email')
    op.drop_column('scholarship', 'eligibility_criteria')
    op.add_column('application', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.drop_column('application', 'notes')
    op.drop_column('application', 'reviewed_by')
    op.drop_column('application', 'reviewed_at')
    op.drop_column('application', 'submission_date')
    op.drop_column('application', 'essay')
    # ### end Alembic commands ###