"""Add database indexes for improved query performance

Revision ID: 46a7343c7624
Revises: 614299f1449d
Create Date: 2025-09-16 22:12:59.966286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a7343c7624'
down_revision = '614299f1449d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_application_reviewed_at'), 'application', ['reviewed_at'], unique=False)
    op.create_index(op.f('ix_application_reviewed_by'), 'application', ['reviewed_by'], unique=False)
    op.create_index(op.f('ix_application_scholarship_id'), 'application', ['scholarship_id'], unique=False)
    op.create_index(op.f('ix_application_status'), 'application', ['status'], unique=False)
    op.create_index(op.f('ix_application_student_id'), 'application', ['student_id'], unique=False)
    op.create_index(op.f('ix_application_submission_date'), 'application', ['submission_date'], unique=False)
    op.create_index(op.f('ix_scholarship_amount'), 'scholarship', ['amount'], unique=False)
    op.create_index(op.f('ix_scholarship_created_at'), 'scholarship', ['created_at'], unique=False)
    op.create_index(op.f('ix_scholarship_created_by'), 'scholarship', ['created_by'], unique=False)
    op.create_index(op.f('ix_scholarship_deadline'), 'scholarship', ['deadline'], unique=False)
    op.create_index(op.f('ix_scholarship_is_active'), 'scholarship', ['is_active'], unique=False)
    op.create_index(op.f('ix_scholarship_title'), 'scholarship', ['title'], unique=False)
    op.drop_constraint(op.f('user_email_key'), 'user', type_='unique')
    op.drop_constraint(op.f('user_email_verification_token_key'), 'user', type_='unique')
    op.drop_constraint(op.f('user_password_reset_token_key'), 'user', type_='unique')
    op.create_index(op.f('ix_user_created_at'), 'user', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_email_verification_expires'), 'user', ['email_verification_expires'], unique=False)
    op.create_index(op.f('ix_user_email_verification_token'), 'user', ['email_verification_token'], unique=True)
    op.create_index(op.f('ix_user_email_verified'), 'user', ['email_verified'], unique=False)
    op.create_index(op.f('ix_user_password_reset_expires'), 'user', ['password_reset_expires'], unique=False)
    op.create_index(op.f('ix_user_password_reset_token'), 'user', ['password_reset_token'], unique=True)
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_index(op.f('ix_user_password_reset_token'), table_name='user')
    op.drop_index(op.f('ix_user_password_reset_expires'), table_name='user')
    op.drop_index(op.f('ix_user_email_verified'), table_name='user')
    op.drop_index(op.f('ix_user_email_verification_token'), table_name='user')
    op.drop_index(op.f('ix_user_email_verification_expires'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_created_at'), table_name='user')
    op.create_unique_constraint(op.f('user_password_reset_token_key'), 'user', ['password_reset_token'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('user_email_verification_token_key'), 'user', ['email_verification_token'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('user_email_key'), 'user', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_scholarship_title'), table_name='scholarship')
    op.drop_index(op.f('ix_scholarship_is_active'), table_name='scholarship')
    op.drop_index(op.f('ix_scholarship_deadline'), table_name='scholarship')
    op.drop_index(op.f('ix_scholarship_created_by'), table_name='scholarship')
    op.drop_index(op.f('ix_scholarship_created_at'), table_name='scholarship')
    op.drop_index(op.f('ix_scholarship_amount'), table_name='scholarship')
    op.drop_index(op.f('ix_application_submission_date'), table_name='application')
    op.drop_index(op.f('ix_application_student_id'), table_name='application')
    op.drop_index(op.f('ix_application_status'), table_name='application')
    op.drop_index(op.f('ix_application_scholarship_id'), table_name='application')
    op.drop_index(op.f('ix_application_reviewed_by'), table_name='application')
    op.drop_index(op.f('ix_application_reviewed_at'), table_name='application')
    # ### end Alembic commands ###