"""Update models with new fields

Revision ID: 88088a8428a6
Revises: cfe03307e546
Create Date: 2025-09-15 22:13:52.001217

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88088a8428a6'
down_revision = 'cfe03307e546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('student_id', sa.Integer(), nullable=False))
    op.add_column('application', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('application_user_id_fkey'), 'application', type_='foreignkey')
    op.create_foreign_key(None, 'application', 'user', ['student_id'], ['id'])
    op.drop_column('application', 'user_id')
    op.drop_column('application', 'essay')
    op.drop_column('application', 'submission_date')
    op.drop_column('scholarship', 'requirements')
    op.add_column('user', sa.Column('name', sa.String(length=64), nullable=False))
    op.add_column('user', sa.Column('password', sa.String(length=128), nullable=False))
    op.add_column('user', sa.Column('role', sa.String(length=20), nullable=False))
    op.drop_constraint(op.f('user_username_key'), 'user', type_='unique')
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('user_username_key'), 'user', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_column('user', 'role')
    op.drop_column('user', 'password')
    op.drop_column('user', 'name')
    op.add_column('scholarship', sa.Column('requirements', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('application', sa.Column('submission_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('application', sa.Column('essay', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('application', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.create_foreign_key(op.f('application_user_id_fkey'), 'application', 'user', ['user_id'], ['id'])
    op.drop_column('application', 'created_at')
    op.drop_column('application', 'student_id')
    # ### end Alembic commands ###